### PR TITLE
Update docker stuff

### PR DESCRIPTION
**Pull request by ethanaobrien**
**Before** merging this pr, you need to create a docker hub account, and an access token.

The `DOCKERHUB_USERNAME` secret should be your docker username
The `DOCKERHUB_TOKEN` secret should be your docker access token

I assumed in this pr, that your username would be `arina999999997`, and your repo name `elichika`. If this is not going to be true, you will need to update the docker workflow with the correct information

This pr will build arm64 and amd64 images

### CODE REVIEW

**Comment by arina999999997** [comment]
Where do I even put the secret? I don't know github

**Comment by arina999999997** [comment]
well never mind, I probably set it up correctly

**Comment by arina999999997** [comment]
Can you confirm that the docs for docker still apply?
If it is, I can merge it and see what happen

**Comment by ethanaobrien** [comment]
oh, yeah

**Comment by ethanaobrien** [comment]
This is ready

**Comment by arina999999997** [comment]
sure let's see if this break absolutely everything

**Comment by yunimoo** [comment]
Awesome! Thanks for creating an official image :)

**Pull request merged**
