### PR TITLE
Add crypto subtle for timing attacks

### PR DESCRIPTION
**Pull request by yunimoo**

### CODE REVIEW

**Comment by arina999999997** [comment]
nice!

**Comment by yunimoo** [comment]
Thanks for feedback, yeah I left it in draft because haven't had chance to check it. It looks fine on my end so let me know if anything else needs to be done

**Comment by arina999999997** [comment]
Thanks, please remove the test file, as it doesn't do anything other than testing.

**Comment by arina999999997** [comment]
Look goods, I'll merge it.

Thanks for the fix!

**Pull request merged**
